#First I want to call libraries
library(dplyr)
library(tidyr)
library(stringr)

#Set working directory
setwd("~/Desktop/GitAndR/Policing/dirty data/Indianapolis")

#I want to call in my datasets (OIS, UOF)
OIS<-read.csv(file = 'Indianapolis Officer Involved Shootings.csv', stringsAsFactors = FALSE)
UOF<-read.csv(file = 'Indianapolis Use of Force Incidents.csv', stringsAsFactors = FALSE)


#Match and replace for OIS
OIS$officerWeaponUsed[OIS$officerWeaponUsed=="IMPD - Duty Handgun"]<-("Duty Handgun")
OIS$officerWeaponUsed[OIS$officerWeaponUsed=="IMPD - Shotgun"]<-("Shotgun")
OIS$officerWeaponUsed[OIS$officerWeaponUsed=="IMPD - Patrol Rifle"]<-("Patrol Rifle")

#Make all null values = N/A for OIS
OIS$occurredDate[OIS$occurredDate==""]<-("N/A")
OIS$division[OIS$division==""]<-("N/A")
OIS$district[OIS$district==""]<-("N/A")
OIS$shift[OIS$shift==""]<-("N/A")
OIS$beat[OIS$beat==""]<-("N/A")
OIS$disposition[OIS$disposition==""]<-("N/A")
OIS$residentWeaponUsed[OIS$residentWeaponUsed==""]<-("N/A")
OIS$officerWeaponUsed[OIS$officerWeaponUsed==""]<-("N/A")
OIS$serviceType[OIS$serviceType==""]<-("N/A")
OIS$residentCondition[OIS$residentCondition==""]<-("N/A")
OIS$officerCondition[OIS$officerCondition==""]<-("N/A")
OIS$residentRace[OIS$residentRace==""]<-("N/A")
OIS$residentSex[OIS$residentSex==""]<-("N/A")
OIS$residentAge[OIS$residentAge==""]<-("N/A")
OIS$officerRace[OIS$officerRace==""]<-("N/A")
OIS$officerSex[OIS$officerSex==""]<-("N/A")
OIS$officerAge[OIS$officerAge==""]<-("N/A")
OIS$officerYearsOfService[OIS$officerYearsOfService==""]<-("N/A")
OIS$officerIdentifier[OIS$officerIdentifier==""]<-("N/A")
OIS$serviceType[OIS$serviceType=="Not Applicable"]<-("N/A")
OIS$residentRace[OIS$residentRace=="Unknown"]<-("N/A")

#Match and replace for UOF
UOF$officerForceType[UOF$officerForceType=="Less Lethal-BPS Gas"]<-("Less Lethal-Bps Gas")
UOF$residentCondition[UOF$residentCondition=="abraisons"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="abrasion"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="Abrasion"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="ABRASION"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="Abrasion to cheek"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="abrassion"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="BLEEDING FROM PRIOR FIGHT"]<-("Bleeding from prior fight")
UOF$residentCondition[UOF$residentCondition=="bloody nose"]<-("Bloody nose")
UOF$residentCondition[UOF$residentCondition=="breathing complaint"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="Broken Bone"]<-("Broken bone")
UOF$residentCondition[UOF$residentCondition=="Broken Tooth"]<-("Broken tooth")
UOF$residentCondition[UOF$residentCondition=="busted tooth"]<-("Broken tooth")
UOF$residentCondition[UOF$residentCondition=="Canine Bite"]<-("Canine bite")
UOF$residentCondition[UOF$residentCondition=="Complaint of Breathing Issue"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="complaint of pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="Complaint of Pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="CS / OC sprayed"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="cs spray"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="cs/oc"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="CSOC"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="difficulty breathing"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="Dislocated Bone"]<-("Dislocated bone")
UOF$residentCondition[UOF$residentCondition=="Dry Stun"]<-("Dry stun")
UOF$residentCondition[UOF$residentCondition=="Fractured Bone"]<-("Fractured bone")
UOF$residentCondition[UOF$residentCondition=="hand cuffing"]<-("Hand cuffing")
UOF$residentCondition[UOF$residentCondition=="head injury"]<-("Head injury")
UOF$residentCondition[UOF$residentCondition=="initial point of contact"]<-("Initial point of contact")
UOF$residentCondition[UOF$residentCondition=="Internal Pain/Discomfort"]<-("Internal pain/Discomfort")
UOF$residentCondition[UOF$residentCondition=="Knee Strikes"]<-("Knee strikes")
UOF$residentCondition[UOF$residentCondition=="Knife Wound"]<-("Knife wound")
UOF$residentCondition[UOF$residentCondition=="loss of skin"]<-("Loss of skin")
UOF$residentCondition[UOF$residentCondition=="Major Bleeding"]<-("Major bleeding")
UOF$residentCondition[UOF$residentCondition=="Major Scrapes"]<-("Major scrapes")
UOF$residentCondition[UOF$residentCondition=="Minor Scrapes"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="No Injury"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="no injury/prong in shirt"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="none"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="none apparant"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="oc sprayed"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="PIN PRICK MIDDLE BACK"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Possible Broken Jaw"]<-("Possible broken jaw")
UOF$residentCondition[UOF$residentCondition=="Prior Knee Injury"]<-("Prior knee injury")
UOF$residentCondition[UOF$residentCondition=="PROBE ENTRY POINTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="probe mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="probe strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Probe strikes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Prong entry"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="prongs from taser cartridge"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture from Probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture from Tazer prong"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture Wound"]<-("Pucture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture Wound From Probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture wound from tazer"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="puncture wound/taser probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="redness"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="Red mark"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="REDNESS"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="redness and skin damage"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="REDNESS DUE TO OC/CS"]<-("OC/CS spray")
UOF$residentCondition[UOF$residentCondition=="Redness from chafing"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="road rash"]<-("Road rash")
UOF$residentCondition[UOF$residentCondition=="scrapes"]<-("Scrapes")
UOF$residentCondition[UOF$residentCondition=="Scratch"]<-("Scrapes")
UOF$residentCondition[UOF$residentCondition=="scratch to left cheek"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="scratch to neck"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="scratches/scrapes"]<-("Scrapes")
UOF$residentCondition[UOF$residentCondition=="SELF SUSTAINED CUT"]<-("Self-sustained cut")
UOF$residentCondition[UOF$residentCondition=="Shoulder Pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="shoulder pain reported later"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="Small cut on nose"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="Small Minor Scrapes"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="small puncture"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Small puncture from taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Small red mark"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="small red mark on cheek"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="Soft Tissue"]<-("Soft tissue")
UOF$residentCondition[UOF$residentCondition=="spray/redness to left eye"]<-("OC/CS spray")
UOF$residentCondition[UOF$residentCondition=="struck by taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Tased"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser entry point"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser marks"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER Probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBE"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe entry"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe entry wound"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBE HITS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBE IMPACTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe inserted"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Probe Mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe marks"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe punctures"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe stuck"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe-abdomen area"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBES"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBES DEPLOYED"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prong"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PRONG"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prong entry points"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PRONG ENTRY POINTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prong entry wound"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prong in face"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PRONG PUNCTURE"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser prong punctures"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prong strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prongs lodged"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser prongs/darts"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser usage"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazed"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazer"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazer probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TAZER PRONG CONTACT POINTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazer prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="trouble breathing"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="two braids pulled out"]<-("Two braids pulled out")
UOF$residentCondition[UOF$residentCondition=="Where female was grabbed"]<-("Grabbed")
UOF$residentCondition[UOF$residentCondition=="Where Taser Prong entered"]<-("Puncture wound/Taser probe")



#Make all null values = N/A for UOF
UOF$id[UOF$id==""]<-("N/A")
UOF$occurredDate[UOF$occurredDate==""]<-("N/A")
UOF$division[UOF$division==""]<-("N/A")
UOF$district[UOF$district==""]<-("N/A")
UOF$shift[UOF$shift==""]<-("N/A")
UOF$beat[UOF$beat==""]<-("N/A")
UOF$useOfForceReason[UOF$useOfForceReason==""]<-("N/A")
UOF$officerForceType[UOF$officerForceType==""]<-("N/A")
UOF$disposition[UOF$disposition==""]<-("N/A")
UOF$serviceType[UOF$serviceType==""]<-("N/A")
UOF$arrestMade[UOF$arrestMade==""]<-("N/A")
UOF$arrestCharges[UOF$arrestCharges==""]<-("N/A")
UOF$residentInjured[UOF$residentInjured==""]<-("N/A")
UOF$residentHospitalized[UOF$residentHospitalized==""]<-("N/A")
UOF$residentCondition[UOF$residentCondition==""]<-("N/A")
UOF$officerInjured[UOF$officerInjured==""]<-("N/A")
UOF$officerHospitalized[UOF$officerHospitalized==""]<-("N/A")
UOF$officerCondition[UOF$officerCondition==""]<-("N/A")
UOF$residentRace[UOF$residentRace==""]<-("N/A")
UOF$residentSex[UOF$residentSex==""]<-("N/A")
UOF$residentAge[UOF$residentAge==""]<-("N/A")
UOF$officerRace[UOF$officerRace==""]<-("N/A")
UOF$officerSex[UOF$officerSex==""]<-("N/A")
UOF$officerAge[UOF$officerAge==""]<-("N/A")
UOF$officerYearsOfService[UOF$officerYearsOfService==""]<-("N/A")
UOF$officerIdentifier[UOF$officerIdentifier==""]<-("N/A")
UOF$residentCondition[UOF$residentCondition=="unknown"]<-("N/A")
UOF$residentCondition[UOF$residentCondition=="unknwon"]<-("N/A")
UOF$residentCondition[UOF$residentCondition=="Possible minor bleeding"]<-("N/A")
UOF$residentCondition[UOF$residentCondition=="none; possible minor bleedin"]<-("N/A")


table(UOF$residentCondition)


