#load dependencies and set working directory
source("ProjectPackageManagement.R")
source("Data Cleaning Functions.R")
PackageDependency()
setwd(here())

#I want to call in my datasets (OIS, UOF)
OIS<-read.csv(file = 'dirty data/Indianapolis/Indianapolis Officer Involved Shootings.csv', stringsAsFactors = FALSE)
UOF<-read.csv(file = 'dirty data/Indianapolis/Indianapolis Use of Force Incidents.csv', stringsAsFactors = FALSE)

### UOF Cleaning ###

#Match and replace for UOF resident condition to make it uniform
UOF$residentCondition[UOF$residentCondition=="abraisons"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="abrasion"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="Abrasion"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="ABRASION"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="Abrasion to cheek"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="abrassion"]<-("Abrasions")
UOF$residentCondition[UOF$residentCondition=="BLEEDING FROM PRIOR FIGHT"]<-("Bleeding from prior fight")
UOF$residentCondition[UOF$residentCondition=="bloody nose"]<-("Bloody nose")
UOF$residentCondition[UOF$residentCondition=="breathing complaint"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="Broken Bone"]<-("Broken bone")
UOF$residentCondition[UOF$residentCondition=="Broken Tooth"]<-("Broken tooth")
UOF$residentCondition[UOF$residentCondition=="busted tooth"]<-("Broken tooth")
UOF$residentCondition[UOF$residentCondition=="Canine Bite"]<-("Canine bite")
UOF$residentCondition[UOF$residentCondition=="Complaint of Breathing Issue"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="Chemical spray"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="complaint of pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="Complaint of Pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="CS / OC sprayed"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="cs spray"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="cs/oc"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="CSOC"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="Cuffing"]<-("Hand cuffing")
UOF$residentCondition[UOF$residentCondition=="difficulty breathing"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="Dislocated Bone"]<-("Dislocated bone")
UOF$residentCondition[UOF$residentCondition=="Dry Stun"]<-("Dry stun")
UOF$residentCondition[UOF$residentCondition=="Fractured Bone"]<-("Fractured bone")
UOF$residentCondition[UOF$residentCondition=="hand cuffing"]<-("Hand cuffing")
UOF$residentCondition[UOF$residentCondition=="head injury"]<-("Head injury")
UOF$residentCondition[UOF$residentCondition=="initial point of contact"]<-("Initial point of contact")
UOF$residentCondition[UOF$residentCondition=="Internal Pain/Discomfort"]<-("Internal pain/Discomfort")
UOF$residentCondition[UOF$residentCondition=="Knee Strikes"]<-("Knee strikes")
UOF$residentCondition[UOF$residentCondition=="Knife Wound"]<-("Knife wound")
UOF$residentCondition[UOF$residentCondition=="loss of skin"]<-("Loss of skin")
UOF$residentCondition[UOF$residentCondition=="Major Bleeding"]<-("Major bleeding")
UOF$residentCondition[UOF$residentCondition=="Major Scrapes"]<-("Major scrapes")
UOF$residentCondition[UOF$residentCondition=="Minor Scrapes"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="Minor Bleeding"]<-("Minor bleeding")
UOF$residentCondition[UOF$residentCondition=="No Injury"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="no injury/prong in shirt"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="none"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="none apparant"]<-("No injuries noted or visible")
UOF$residentCondition[UOF$residentCondition=="oc sprayed"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="Pain to right hand"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="pepper spray"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="PIN PRICK MIDDLE BACK"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Possible Broken Jaw"]<-("Possible broken jaw")
UOF$residentCondition[UOF$residentCondition=="Prior Knee Injury"]<-("Prior knee injury")
UOF$residentCondition[UOF$residentCondition=="PROBE ENTRY POINTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="probe mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="probe strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Probe strikes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Prong entry"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="prongs from taser cartridge"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture from Probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture from Tazer prong"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture Wound"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture Wound From Probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Puncture wound from tazer"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="puncture wound/taser probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="redness"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="Red mark"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="REDNESS"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="redness and skin damage"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="REDNESS DUE TO OC/CS"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="Redness from chafing"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="road rash"]<-("Road rash")
UOF$residentCondition[UOF$residentCondition=="scrapes"]<-("Scrapes")
UOF$residentCondition[UOF$residentCondition=="Scratch"]<-("Scrapes")
UOF$residentCondition[UOF$residentCondition=="scratch to left cheek"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="scratch to neck"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="scratches/scrapes"]<-("Scrapes")
UOF$residentCondition[UOF$residentCondition=="SELF SUSTAINED CUT"]<-("Self-sustained cut")
UOF$residentCondition[UOF$residentCondition=="Shoulder Pain"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="shoulder pain reported later"]<-("Complaint of pain")
UOF$residentCondition[UOF$residentCondition=="Small cut on nose"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="Small Minor Scrapes"]<-("Minor scrapes")
UOF$residentCondition[UOF$residentCondition=="small puncture"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Small puncture from taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Small red mark"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="small red mark on cheek"]<-("Redness")
UOF$residentCondition[UOF$residentCondition=="Soft Tissue"]<-("Soft tissue")
UOF$residentCondition[UOF$residentCondition=="spray/redness to left eye"]<-("CS/OC spray")
UOF$residentCondition[UOF$residentCondition=="struck by taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Tased"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser entry point"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser marks"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER Probe"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBE"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe entry"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe entry wound"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBE HITS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBE IMPACTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe inserted"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Probe Mark"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe marks"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe punctures"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probe stuck"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probe-abdomen area"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBES"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PROBES DEPLOYED"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prong"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PRONG"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prong entry points"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PRONG ENTRY POINTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prong entry wound"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prong in face"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TASER PRONG PUNCTURE"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser prong punctures"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prong strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser Prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="Taser prongs lodged"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser prongs/darts"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser strike"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="taser usage"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazed"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazer"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazer probes"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="TAZER PRONG CONTACT POINTS"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="tazer prongs"]<-("Puncture wound/Taser probe")
UOF$residentCondition[UOF$residentCondition=="trouble breathing"]<-("Breathing complaint")
UOF$residentCondition[UOF$residentCondition=="two braids pulled out"]<-("Two braids pulled out")
UOF$residentCondition[UOF$residentCondition=="Where female was grabbed"]<-("Grabbed")
UOF$residentCondition[UOF$residentCondition=="Where Taser Prong entered"]<-("Puncture wound/Taser probe")

#Find and replace for Officer Condition to make it more uniform
UOF$officerCondition[UOF$officerCondition=="(kicked) sudden short pain"]<-("Kicked")
UOF$officerCondition[UOF$officerCondition=="Abrasion to forehead"]<-("Abrasions")
UOF$officerCondition[UOF$officerCondition=="ABRASION-RIGHT INDEX FINGER"]<-("Abrasions")
UOF$officerCondition[UOF$officerCondition=="abrasions"]<-("Abrasions")
UOF$officerCondition[UOF$officerCondition=="Back Strain"]<-("Back strain")
UOF$officerCondition[UOF$officerCondition=="BACK STRAIN"]<-("Back strain")
UOF$officerCondition[UOF$officerCondition=="Battery bodily fluid"]<-("Battery by bodily fluid/waste")
UOF$officerCondition[UOF$officerCondition=="Battery by bodily waste"]<-("Battery by bodily fluid/waste")
UOF$officerCondition[UOF$officerCondition=="Bite Mark"]<-("Bite mark")
UOF$officerCondition[UOF$officerCondition=="Blod Clot to Right Eye"]<-("Blood clot to right eye")
UOF$officerCondition[UOF$officerCondition=="blood exposure"]<-("Blood exposure")
UOF$officerCondition[UOF$officerCondition=="Blood Exposure to Hep C"]<-("Blood exposure to Hep C")
UOF$officerCondition[UOF$officerCondition=="Blood on cheek"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="BLOOD TRANSFER"]<-("Blood transfer")
UOF$officerCondition[UOF$officerCondition=="BODY FLUID"]<-("Exposure to bodily fluid/waste")
UOF$officerCondition[UOF$officerCondition=="BODY FUID"]<-("Exposure to bodily fluid/waste")
UOF$officerCondition[UOF$officerCondition=="Broken Bone"]<-("Broken bone")
UOF$officerCondition[UOF$officerCondition=="BROKEN NAIL"]<-("Broken nail")
UOF$officerCondition[UOF$officerCondition=="Broken Tooth"]<-("Broken tooth")
UOF$officerCondition[UOF$officerCondition=="bruised left eyebrow"]<-("Bruising")
UOF$officerCondition[UOF$officerCondition=="bruising and pain"]<-("Bruising")
UOF$officerCondition[UOF$officerCondition=="burning sensation and rednes"]<-("Burning sensation")
UOF$officerCondition[UOF$officerCondition=="Cervical Disc Compression"]<-("Cervical disc compression")
UOF$officerCondition[UOF$officerCondition=="complaint of pain"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="Complaint of Pain"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="COMPLAINT OF PAIN"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="COMPLAINT OF PAIN RIGHT"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="Complaint of pain to arm"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="concussion"]<-("Concussion")
UOF$officerCondition[UOF$officerCondition=="contact"]<-("Contact")
UOF$officerCondition[UOF$officerCondition=="Discomfort"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="Dislocated Bone"]<-("Dislocated bone")
UOF$officerCondition[UOF$officerCondition=="exposure to blood"]<-("Blood exposure")
UOF$officerCondition[UOF$officerCondition=="Exposure to blood"]<-("Blood exposure")
UOF$officerCondition[UOF$officerCondition=="Fractured Bone"]<-("Fractured bone")
UOF$officerCondition[UOF$officerCondition=="Gunshot Wound"]<-("Gunshot wound")
UOF$officerCondition[UOF$officerCondition=="Head Bump"]<-("Head bump")
UOF$officerCondition[UOF$officerCondition=="head butt, nothing visible"]<-("Head-butted")
UOF$officerCondition[UOF$officerCondition=="hit to leg"]<-("Hit")
UOF$officerCondition[UOF$officerCondition=="hit with closed fist"]<-("Hit")
UOF$officerCondition[UOF$officerCondition=="Internal Pain/Discomfort"]<-("Internal pain/Discomfort")
UOF$officerCondition[UOF$officerCondition=="Kick no injury"]<-("Kicked")
UOF$officerCondition[UOF$officerCondition=="Kick to the chest"]<-("Kicked")
UOF$officerCondition[UOF$officerCondition=="KICKED"]<-("Kicked")
UOF$officerCondition[UOF$officerCondition=="Knife Wound"]<-("Knife wound")
UOF$officerCondition[UOF$officerCondition=="knot to back of head"]<-("Head bump")
UOF$officerCondition[UOF$officerCondition=="LIGAMENT TEAR"]<-("Ligament tear")
UOF$officerCondition[UOF$officerCondition=="Major Bleeding"]<-("Major bleeding")
UOF$officerCondition[UOF$officerCondition=="Minor Abrasion"]<-("Abrasions")
UOF$officerCondition[UOF$officerCondition=="minor bleeding"]<-("Minor bleeding")
UOF$officerCondition[UOF$officerCondition=="Minor Bleeding"]<-("Minor bleeding")
UOF$officerCondition[UOF$officerCondition=="minor cuts"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="minor scrape to finger"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="Minor Scrapes"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="Missed kick"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="Needle Stick"]<-("Sticked by needle")
UOF$officerCondition[UOF$officerCondition=="no injury"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="No injury,just hurt feelings"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="No injury/strike only"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="none"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="None"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="NONE"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="numb feeling elbow to finger"]<-("Numbness")
UOF$officerCondition[UOF$officerCondition=="ofc pulled arm away b4 bite"]<-("No injuries noted or visible")
UOF$officerCondition[UOF$officerCondition=="officer kicked"]<-("Kicked")
UOF$officerCondition[UOF$officerCondition=="Pain and tightness"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="pain to right knee"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="PAIN TO SHOULDER"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="Pain/Discomfort"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="Possible Rotator cuff tear"]<-("Possible rotator cuff tear")
UOF$officerCondition[UOF$officerCondition=="pulled hamstring"]<-("Sprain/Strain")
UOF$officerCondition[UOF$officerCondition=="Pushed/ Shoved at listed"]<-("Pushed/shoved")
UOF$officerCondition[UOF$officerCondition=="red mark"]<-("Redness")
UOF$officerCondition[UOF$officerCondition=="REDNESS"]<-("Redness")
UOF$officerCondition[UOF$officerCondition=="redness/skin irritation"]<-("Redness")
UOF$officerCondition[UOF$officerCondition=="right knee"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="right middle finger nail bed"]<-("Complaint of pain")
UOF$officerCondition[UOF$officerCondition=="Saliva in mouth"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="scraped right knee"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="SCRATCH MARKS"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="Scratch on right hand"]<-("Minor scrapes")
UOF$officerCondition[UOF$officerCondition=="SLAP TO THE FACE"]<-("Slapped")
UOF$officerCondition[UOF$officerCondition=="Spit"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="spit on"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="Spit on"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="SPIT ON"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="Spit on face"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="spit on right forearm"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="splattering blood  only"]<-("Blood exposure")
UOF$officerCondition[UOF$officerCondition=="Sprain/Swelling"]<-("Sprain/Strain")
UOF$officerCondition[UOF$officerCondition=="STRAINED HAMSTRING MUSCLE"]<-("Sprain/Strain")
UOF$officerCondition[UOF$officerCondition=="Strained hip/thigh muscle"]<-("Sprain/Strain")
UOF$officerCondition[UOF$officerCondition=="Strained Ligament"]<-("Sprain/Strain")
UOF$officerCondition[UOF$officerCondition=="Struck but not injured"]<-("Hit")
UOF$officerCondition[UOF$officerCondition=="Susp spit in Officer's face"]<-("Spit on/at")
UOF$officerCondition[UOF$officerCondition=="TASER PROBE STICK"]<-("Puncture wound/Taser probe")
UOF$officerCondition[UOF$officerCondition=="torn rotator cuff"]<-("Torn rotator cuff")

#Find and replace misc.
UOF$shift[UOF$shift=="Swat Section"]<-("SWAT Section")
UOF$beat[UOF$beat=="Swat Unit"]<-("SWAT Unit")
UOF$residentRace[UOF$residentRace=="Blace"]<-("Black")
UOF$residentRace[UOF$residentRace=="Native Amer"]<-("Native American")
UOF$officerForceType[UOF$officerForceType=="Less Lethal-BPS Gas"]<-("Less Lethal-Bps Gas")


#Make all null values = N/A for UOF
UOF = ReplwNull(UOF)
UOF$residentCondition[UOF$residentCondition=="Possible minor bleeding"]<-(NA)
UOF$residentCondition[UOF$residentCondition=="none; possible minor bleedin"]<-(NA)
UOF$residentRace[UOF$residentRace=="Other"]<-(NA)

#Making a Force Binning column and binning the force type used
UOF$ForceBinning = UOF$officerForceType

UOF_FixLevels <- UOF
UOF_FixLevels <- UOF_FixLevels %>%
  mutate(ForceBinning = case_when(
    str_detect(ForceBinning, "Lethal-Vehicle") ~ "3",
    str_detect(ForceBinning, "Lethal-Handgun") ~ "3",
    str_detect(ForceBinning, "Less Lethal") ~ "2",
    str_detect(ForceBinning, "Canine") ~ "2",
    str_detect(ForceBinning, "Physical") ~ "1",
    TRUE ~ ForceBinning
  ))

#making N/As in the column regular NAs
UOF_FixLevels$ForceBinning[UOF_FixLevels$ForceBinning=="N/A"]<-NA


### OIS Cleaning ###

#Make all null values = N/A for OIS
OIS = ReplwNull(OIS)

#Match and replace for OIS
OIS$officerWeaponUsed[OIS$officerWeaponUsed=="IMPD - Duty Handgun"]<-("Duty Handgun")
OIS$officerWeaponUsed[OIS$officerWeaponUsed=="IMPD - Shotgun"]<-("Shotgun")
OIS$officerWeaponUsed[OIS$officerWeaponUsed=="IMPD - Patrol Rifle"]<-("Patrol Rifle")


### Saving Cleaned Datasets ###

write.csv(OIS,"clean data/Indianapolis/OIS.csv",row.names = FALSE)
write.csv(UOF_FixLevels,"clean data/Indianapolis/UOF.csv",row.names = FALSE)
